# @name loginLink

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Jim"
}

###

@refreshToken = {{loginLink.response.body.$.refreshToken}}

# @name tokenLink

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

###

@token = {{tokenLink.response.body.$.accessToken}}

# @name = posts

GET http://localhost:3000/posts
Authorization: Bearer {{token}}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "{{refreshToken}}"
}

